"""Train the XGBoost outbreak model on 3 simulated years and backtest it on the held-out 4th year
against EARS-only and the fused NeerNetra tiering."""
import math
from datetime import date
from statistics import median

import numpy as np
import xgboost as xgb
from sklearn.metrics import roc_auc_score

from app.engine import ears
from app.engine.book import Book
from app.engine.features import GROUP_LABELS, NAMES, feature_row, h2s_uncleared
from app.engine.history import HORIZON, episodes, generate_history, labels, outbreak_flags
from app.engine.model import GROUP_INDEX
from app.engine.tiers import ANOMALY_NTU, tier_for
from app.engine.villages import VILLAGES

PARAMS = {
    "objective": "binary:logistic",
    "eval_metric": "logloss",
    "max_depth": 4,
    "eta": 0.05,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "min_child_weight": 3,
    "lambda": 2.0,
    "seed": 7,
    "nthread": 4,
}
ROUNDS = 300
WARMUP_DAYS = 14
ALARM_MERGE_GAP = 2
EARLY_WINDOW = 7
TRAIN_END = date(2024, 12, 31)
VALIDATION_FOLDS = [(date(2022, 12, 31), date(2023, 12, 31)), (date(2023, 12, 31), date(2024, 12, 31))]
THRESHOLD_GRID = [round(x, 2) for x in np.arange(0.05, 0.91, 0.01)]
SIGMA_FLOORS = [1.0, 1.5, 2.0]
RECALL_TARGET = 0.85

OUTBREAK_DEFINITION = (
    "Outbreak day: true symptom onsets in a village over 3 days reach max(12, 3.2 per 1,000 people); "
    "outbreak days less than 6 days apart form one episode, whose onset is its first day. "
    "Detected: an alarm fires between 7 days before onset and the end of the episode; lead = onset - first alarm day. "
    "Alarm days less than 3 days apart form one alarm; a false alarm overlaps no episode's [onset - 7, end] window. "
    "The model predicts P(outbreak day within the next 7 days)."
)
SYNTHETIC_DISCLAIMER = (
    "All data are synthetic: 4 years x 12 villages generated by NeerNetra's causal simulator "
    "(seasonal rain, turbidity, faecal contamination with upstream coupling and random non-rain events, "
    "incubation, under-reported and delayed case reports, sensor gaps and sparse field tests). "
    "Metrics show the method on realistic synthetic data; they are not a field-validated performance claim."
)


class Frame:
    """All model inputs and detector outputs for every village-day of a history."""

    def __init__(self, book: Book):
        self.book = book
        n = book.days
        self.last = n - 1 - HORIZON
        self.flags = [outbreak_flags(book, i) for i in range(len(VILLAGES))]
        self.episodes = [episodes(f) for f in self.flags]
        self.y = np.array([labels(f) for f in self.flags])
        self.ears = np.zeros((len(VILLAGES), n), dtype=bool)
        self.cases3 = np.zeros((len(VILLAGES), n), dtype=int)
        self.anomaly = np.zeros((len(VILLAGES), n), dtype=bool)
        rows, index = [], []
        for i, v in enumerate(VILLAGES):
            s = book.series[i]
            for d in range(WARMUP_DAYS, self.last + 1):
                self.ears[i, d] = ears.scores(s.cases, d)[3]
                self.cases3[i, d] = sum(s.cases[d - 2:d + 1])
                turb3 = [t for t in s.turb[d - 2:d + 1] if not math.isnan(t)]
                self.anomaly[i, d] = (bool(turb3) and max(turb3) > ANOMALY_NTU) or h2s_uncleared(s, d)
                rows.append(feature_row(book, i, d))
                index.append((i, d))
        self.X = np.array(rows)
        self.index = np.array(index)

    def rows_between(self, lo: int, hi: int) -> np.ndarray:
        d = self.index[:, 1]
        return np.where((d >= lo) & (d <= hi))[0]

    def labels_of(self, rows: np.ndarray) -> np.ndarray:
        return self.y[self.index[rows, 0], self.index[rows, 1]]


def fit(X: np.ndarray, y: np.ndarray) -> xgb.Booster:
    return xgb.train(PARAMS, xgb.DMatrix(X, label=y, feature_names=NAMES, missing=np.nan), ROUNDS)


def risk_matrix(fr: Frame, booster: xgb.Booster, rows: np.ndarray) -> np.ndarray:
    risk = np.zeros(fr.y.shape)
    p = booster.predict(xgb.DMatrix(fr.X[rows], feature_names=NAMES, missing=np.nan))
    risk[fr.index[rows, 0], fr.index[rows, 1]] = p
    return risk


def neernetra_alarm(fr: Frame, risk: np.ndarray, threshold: float) -> np.ndarray:
    alarm = np.zeros(fr.y.shape, dtype=bool)
    for i, v in enumerate(VILLAGES):
        for d in range(WARMUP_DAYS, fr.last + 1):
            tier = tier_for(risk[i, d], threshold, fr.ears[i, d], fr.cases3[i, d], v.outbreak_cases_3d, fr.anomaly[i, d])
            alarm[i, d] = tier in ("warning", "outbreak")
    return alarm


def alarm_events(days: np.ndarray, lo: int) -> list[tuple[int, int]]:
    out: list[list[int]] = []
    for d in np.where(days)[0]:
        d = int(d) + lo
        if out and d - out[-1][1] <= ALARM_MERGE_GAP + 1:
            out[-1][1] = d
        else:
            out.append([d, d])
    return [(a, b) for a, b in out]


def tally(fr: Frame, alarm: np.ndarray, lo: int, hi: int) -> dict:
    leads: list[int] = []
    total = true_events = false_events = 0
    for i in range(len(VILLAGES)):
        windows = [(s - EARLY_WINDOW, e) for s, e in fr.episodes[i]]
        for s, e in fr.episodes[i]:
            if not lo + EARLY_WINDOW <= s <= hi:
                continue
            total += 1
            hits = [d for d in range(s - EARLY_WINDOW, min(e, hi) + 1) if alarm[i, d]]
            if hits:
                leads.append(s - hits[0])
        for a, b in alarm_events(alarm[i, lo:hi + 1], lo):
            if any(a <= we and b >= ws for ws, we in windows):
                true_events += 1
            else:
                false_events += 1
    return {"leads": leads, "episodes": total, "true": true_events, "false": false_events,
            "villageDays": len(VILLAGES) * (hi - lo + 1)}


def metrics(method: str, tallies: list[dict]) -> dict:
    leads = [x for t in tallies for x in t["leads"]]
    episodes = sum(t["episodes"] for t in tallies)
    true_events = sum(t["true"] for t in tallies)
    false_events = sum(t["false"] for t in tallies)
    return {
        "method": method,
        "recall": round(len(leads) / episodes, 3) if episodes else 0.0,
        "precision": round(true_events / (true_events + false_events), 3) if true_events + false_events else 0.0,
        "falseAlarmsPer100VillageDays": round(100 * false_events / sum(t["villageDays"] for t in tallies), 3),
        "medianLeadDays": float(median(leads)) if leads else None,
        "detectedEpisodes": len(leads),
    }


def f2(m: dict) -> float:
    p, r = m["precision"], m["recall"]
    return 5 * p * r / (4 * p + r) if p + r else 0.0


def validate(fr: Frame, book: Book) -> tuple[float, dict]:
    """Expanding-window validation inside the training period: fit on 2022 -> score 2023,
    fit on 2022-23 -> score 2024, pooled. Operating point: the fewest false alarms among thresholds whose
    fused-alarm recall reaches RECALL_TARGET (falling back to the best F2 if none does)."""
    folds = []
    for fit_end, val_end in VALIDATION_FOLDS:
        fe, ve = book.index_of(fit_end), book.index_of(val_end)
        rows = fr.rows_between(WARMUP_DAYS, fe - HORIZON)
        model = fit(fr.X[rows], fr.labels_of(rows))
        folds.append((risk_matrix(fr, model, fr.rows_between(fe + 1, ve)), fe + 1, ve))
    best = None
    for t in THRESHOLD_GRID:
        m = metrics("NeerNetra", [tally(fr, neernetra_alarm(fr, risk, t), lo, hi) for risk, lo, hi in folds])
        if best is None or rank(m) >= rank(best[1]):
            best = (t, m)
    return best


def rank(m: dict) -> tuple:
    meets = m["recall"] >= RECALL_TARGET
    return (meets, -m["falseAlarmsPer100VillageDays"] if meets else f2(m))


def train_and_backtest(log=print) -> tuple[xgb.Booster, float, float, dict]:
    """EARS sigma floor and ML threshold are chosen jointly by validation inside 2022-24 only;
    the final model is refit on 2022-24 and scored once on the held-out 2025."""
    book = generate_history()
    log(f"[engine] simulated {book.days} days x {len(VILLAGES)} villages")
    train_end = book.index_of(TRAIN_END)
    best = None
    for floor in SIGMA_FLOORS:
        ears.SIGMA_FLOOR = floor
        fr = Frame(book)
        threshold, m = validate(fr, book)
        log(f"[engine] validation 2023-24: EARS sigma floor {floor}, threshold {threshold:.2f}: recall {m['recall']:.2f}, "
            f"precision {m['precision']:.2f}, false alarms/100 village-days {m['falseAlarmsPer100VillageDays']:.2f}")
        if best is None or rank(m) > rank(best[2]):
            best = (floor, threshold, m, fr)
    floor, threshold, _, fr = best
    ears.SIGMA_FLOOR = floor
    train_rows = fr.rows_between(WARMUP_DAYS, train_end - HORIZON)
    test_rows = fr.rows_between(train_end + 1, fr.last)
    test_lo, test_hi = train_end + 1, fr.last

    booster = fit(fr.X[train_rows], fr.labels_of(train_rows))
    risk = risk_matrix(fr, booster, test_rows)
    y_test = fr.labels_of(test_rows)
    auc = roc_auc_score(y_test, risk[fr.index[test_rows, 0], fr.index[test_rows, 1]])

    runs = [
        ("EARS-only", tally(fr, fr.ears, test_lo, test_hi)),
        ("XGBoost-only", tally(fr, risk >= threshold, test_lo, test_hi)),
        ("NeerNetra (XGBoost + EARS)", tally(fr, neernetra_alarm(fr, risk, threshold), test_lo, test_hi)),
    ]
    methods = [metrics(name, [t]) for name, t in runs]
    ears_leads, ml_leads = runs[0][1]["leads"], runs[1][1]["leads"]
    all_leads = ml_leads + ears_leads
    lo_bin = min([-3, *all_leads])
    histogram = [{"leadDays": k, "ml": ml_leads.count(k), "ears": ears_leads.count(k)} for k in range(lo_bin, EARLY_WINDOW + 1)]

    contrib = booster.predict(xgb.DMatrix(fr.X[test_rows], feature_names=NAMES, missing=np.nan), pred_contribs=True)
    mean_abs = np.abs(contrib[:, :-1]).mean(axis=0)
    grouped = {g: float(mean_abs[idx].sum()) for g, idx in GROUP_INDEX.items()}
    total = sum(grouped.values())
    importance = sorted(
        ({"feature": g, "label": GROUP_LABELS[g], "importance": round(val / total, 4)} for g, val in grouped.items()),
        key=lambda x: -x["importance"],
    )

    card = {
        "model": f"XGBoost gradient-boosted trees ({ROUNDS} trees, depth {PARAMS['max_depth']}, {len(NAMES)} features) "
                 f"with TreeSHAP explanations, fused with CDC EARS C2/C3 (sigma floor {floor}); threshold and floor chosen "
                 f"on 2023-24 validation for >= {RECALL_TARGET:.0%} outbreak recall at the fewest false alarms",
        "trainPeriod": f"{book.date_of(WARMUP_DAYS).isoformat()} to {TRAIN_END.isoformat()}",
        "testPeriod": f"{book.date_of(test_lo).isoformat()} to {book.date_of(test_hi).isoformat()}",
        "villages": len(VILLAGES),
        "trainRows": int(len(train_rows)),
        "testRows": int(len(test_rows)),
        "outbreakDefinition": OUTBREAK_DEFINITION,
        "syntheticDisclaimer": SYNTHETIC_DISCLAIMER,
        "auc": round(float(auc), 3),
        "threshold": threshold,
        "testEpisodes": runs[0][1]["episodes"],
        "methods": methods,
        "leadTimeHistogram": histogram,
        "featureImportance": importance,
    }
    return booster, threshold, floor, card


def summary(card: dict) -> str:
    lines = [
        f"[engine] backtest {card['testPeriod']}: {card['testEpisodes']} outbreak episodes, "
        f"AUC {card['auc']:.3f}, threshold {card['threshold']:.2f}",
        f"[engine] {'method':<28}{'recall':>8}{'precision':>11}{'FA/100vd':>10}{'lead(d)':>9}",
    ]
    for m in card["methods"]:
        lead = "-" if m["medianLeadDays"] is None else f"{m['medianLeadDays']:+.1f}"
        lines.append(f"[engine] {m['method']:<28}{m['recall']:>8.2f}{m['precision']:>11.2f}{m['falseAlarmsPer100VillageDays']:>10.2f}{lead:>9}")
    return "\n".join(lines)
